export const ACTION_TYPES = {
  INCREMENT_ITEM_IN_CART: "INCREMENT_ITEM_IN_CART",
  DECREMENT_ITEM_IN_CART: "DECREMENT_ITEM_IN_CART",
  CHANGE_CUISINE: "CHANGE_CUISINE",
  SAVE_MENU_DATA: "SAVE_MENU_DATA",
};
